nginx:
    build: ./nginx
    links:
        - node
    ports:
        - "80:80"
node:
    build: ./node
    ports:
        - "3000:3000"
    links:
        - redis
        - mysql
    volumes:
        - ../FamilySchoolApi:/src
redis:
    image: redis
    ports:
        - "6379"
mysql:
    build: ./mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=redhat
        - MYSQL_DATABASE=familySchool